#!/bin/sh /etc/rc.common
START=95
USE_PROCD=1

start_service() {
	config_load wol-api
	config_get enabled main enabled 1
	config_get host main host '0.0.0.0'
	config_get port main port '8037'
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/uhttpd -f -h /www -r OpenWrt -x /cgi-bin -p ${host}:${port}
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "wol-api"
}
