#!/bin/sh /etc/rc.common
START=95
USE_PROCD=1

SERVICE_NAME="wol-api"

start_service() {
	config_load wol-api
	config_get enabled main enabled 1
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command /usr/bin/python3 /usr/libexec/wol-api/server.py
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "wol-api"
}
